//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASHIONWS.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class BaiViet
    {
        public int BaiVietID { get; set; }
        public string TuaBaiViet { get; set; }
        public string NoiDung { get; set; }
        public int TheLoai { get; set; }
        public string HinhDaiDien { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public Nullable<int> UserId { get; set; }
        public string BiDanh { get; set; }
    }
}
