//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASHIONWS.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class PhanLoai
    {
        public PhanLoai()
        {
            this.Nhomsps = new HashSet<Nhomsp>();
        }

        public int PhanLoaiID { get; set; }
        public string TenPhanLoai { get; set; }
        public string BiDanh { get; set; }
    
        public virtual ICollection<Nhomsp> Nhomsps { get; set; }
    }
}
