//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace FASHIONWS.WS_DienTu {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DienTuSoap", Namespace="http://microsoft.com/webservices/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vw_SanPham[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class DienTu : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocSanPhamOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocSanPhamTheoTenOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocSanPhamTheoNsxLoaispOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DienTu() {
            this.Url = global::FASHIONWS.Properties.Settings.Default.FASHIONWS_WS_DienTu_DienTu;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event DocSanPhamCompletedEventHandler DocSanPhamCompleted;
        
        /// <remarks/>
        public event DocSanPhamTheoTenCompletedEventHandler DocSanPhamTheoTenCompleted;
        
        /// <remarks/>
        public event DocSanPhamTheoNsxLoaispCompletedEventHandler DocSanPhamTheoNsxLoaispCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/HelloWorld", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/DocSanPham", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vw_SanPham[] DocSanPham() {
            object[] results = this.Invoke("DocSanPham", new object[0]);
            return ((vw_SanPham[])(results[0]));
        }
        
        /// <remarks/>
        public void DocSanPhamAsync() {
            this.DocSanPhamAsync(null);
        }
        
        /// <remarks/>
        public void DocSanPhamAsync(object userState) {
            if ((this.DocSanPhamOperationCompleted == null)) {
                this.DocSanPhamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocSanPhamOperationCompleted);
            }
            this.InvokeAsync("DocSanPham", new object[0], this.DocSanPhamOperationCompleted, userState);
        }
        
        private void OnDocSanPhamOperationCompleted(object arg) {
            if ((this.DocSanPhamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocSanPhamCompleted(this, new DocSanPhamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/DocSanPhamTheoTen", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vw_SanPham[] DocSanPhamTheoTen(string TenSanPham) {
            object[] results = this.Invoke("DocSanPhamTheoTen", new object[] {
                        TenSanPham});
            return ((vw_SanPham[])(results[0]));
        }
        
        /// <remarks/>
        public void DocSanPhamTheoTenAsync(string TenSanPham) {
            this.DocSanPhamTheoTenAsync(TenSanPham, null);
        }
        
        /// <remarks/>
        public void DocSanPhamTheoTenAsync(string TenSanPham, object userState) {
            if ((this.DocSanPhamTheoTenOperationCompleted == null)) {
                this.DocSanPhamTheoTenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocSanPhamTheoTenOperationCompleted);
            }
            this.InvokeAsync("DocSanPhamTheoTen", new object[] {
                        TenSanPham}, this.DocSanPhamTheoTenOperationCompleted, userState);
        }
        
        private void OnDocSanPhamTheoTenOperationCompleted(object arg) {
            if ((this.DocSanPhamTheoTenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocSanPhamTheoTenCompleted(this, new DocSanPhamTheoTenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/DocSanPhamTheoNsxLoaisp", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vw_SanPham[] DocSanPhamTheoNsxLoaisp(string NhaSanXuat, string LoaiSanPham) {
            object[] results = this.Invoke("DocSanPhamTheoNsxLoaisp", new object[] {
                        NhaSanXuat,
                        LoaiSanPham});
            return ((vw_SanPham[])(results[0]));
        }
        
        /// <remarks/>
        public void DocSanPhamTheoNsxLoaispAsync(string NhaSanXuat, string LoaiSanPham) {
            this.DocSanPhamTheoNsxLoaispAsync(NhaSanXuat, LoaiSanPham, null);
        }
        
        /// <remarks/>
        public void DocSanPhamTheoNsxLoaispAsync(string NhaSanXuat, string LoaiSanPham, object userState) {
            if ((this.DocSanPhamTheoNsxLoaispOperationCompleted == null)) {
                this.DocSanPhamTheoNsxLoaispOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocSanPhamTheoNsxLoaispOperationCompleted);
            }
            this.InvokeAsync("DocSanPhamTheoNsxLoaisp", new object[] {
                        NhaSanXuat,
                        LoaiSanPham}, this.DocSanPhamTheoNsxLoaispOperationCompleted, userState);
        }
        
        private void OnDocSanPhamTheoNsxLoaispOperationCompleted(object arg) {
            if ((this.DocSanPhamTheoNsxLoaispCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocSanPhamTheoNsxLoaispCompleted(this, new DocSanPhamTheoNsxLoaispCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class vw_SanPham : EntityObject {
        
        private int sanPhamIDField;
        
        private string tenSanPhamField;
        
        private string gioiThieuField;
        
        private int donGiaField;
        
        private string hinhField;
        
        private int nhaSanXuatIDField;
        
        private int loaiSanPhamIDField;
        
        private System.DateTime ngayCapNhatField;
        
        private bool hetHangField;
        
        private string biDanhField;
        
        private string tenLoaiSanPhamField;
        
        private string tenNhaSanXuatField;
        
        /// <remarks/>
        public int SanPhamID {
            get {
                return this.sanPhamIDField;
            }
            set {
                this.sanPhamIDField = value;
            }
        }
        
        /// <remarks/>
        public string TenSanPham {
            get {
                return this.tenSanPhamField;
            }
            set {
                this.tenSanPhamField = value;
            }
        }
        
        /// <remarks/>
        public string GioiThieu {
            get {
                return this.gioiThieuField;
            }
            set {
                this.gioiThieuField = value;
            }
        }
        
        /// <remarks/>
        public int DonGia {
            get {
                return this.donGiaField;
            }
            set {
                this.donGiaField = value;
            }
        }
        
        /// <remarks/>
        public string Hinh {
            get {
                return this.hinhField;
            }
            set {
                this.hinhField = value;
            }
        }
        
        /// <remarks/>
        public int NhaSanXuatID {
            get {
                return this.nhaSanXuatIDField;
            }
            set {
                this.nhaSanXuatIDField = value;
            }
        }
        
        /// <remarks/>
        public int LoaiSanPhamID {
            get {
                return this.loaiSanPhamIDField;
            }
            set {
                this.loaiSanPhamIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public bool HetHang {
            get {
                return this.hetHangField;
            }
            set {
                this.hetHangField = value;
            }
        }
        
        /// <remarks/>
        public string BiDanh {
            get {
                return this.biDanhField;
            }
            set {
                this.biDanhField = value;
            }
        }
        
        /// <remarks/>
        public string TenLoaiSanPham {
            get {
                return this.tenLoaiSanPhamField;
            }
            set {
                this.tenLoaiSanPhamField = value;
            }
        }
        
        /// <remarks/>
        public string TenNhaSanXuat {
            get {
                return this.tenNhaSanXuatField;
            }
            set {
                this.tenNhaSanXuatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vw_SanPham))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vw_SanPham))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DocSanPhamCompletedEventHandler(object sender, DocSanPhamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocSanPhamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocSanPhamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vw_SanPham[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vw_SanPham[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DocSanPhamTheoTenCompletedEventHandler(object sender, DocSanPhamTheoTenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocSanPhamTheoTenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocSanPhamTheoTenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vw_SanPham[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vw_SanPham[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DocSanPhamTheoNsxLoaispCompletedEventHandler(object sender, DocSanPhamTheoNsxLoaispCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocSanPhamTheoNsxLoaispCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocSanPhamTheoNsxLoaispCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vw_SanPham[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vw_SanPham[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591